#!/bin/bash

cp .functions_operation ..
cp .bash_prompt ..
cp .tmux.conf ..

cp .aliases ../.aliases
cp .ssh_config ../.ssh/config

cp .bashrc ../.bashrc
cp .bash_profile ../.bash_profile
cp .vimrc ../.vimrc

if [ ! -d ../.vim ]; then
    cp -r .vim ../.vim
fi

#cp .gitignore ..
#cp .rc_docker ..
#cp .rc_docker_functions ..

source ~/.bash_profile
